# LambdaTest AI Cloud Configuration
project_id: "01JA8MD4E2RFG85ZMADXAJE82V"
folder_id: "01KB5F62X53WDBKD8RDXYQ7AVC"
assignee: 2135709
environment_id: 164599
test_url: "viaxco-ecommerce-demo.netlify.app"